---
- name: "Facts:Netconf"
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: gathering info from device
      junos_get_facts: host={{ inventory_hostname }}
      register: junos 
    - name: version
      debug: msg={{ junos.facts.version }}
    - name: serial-number
      debug: msg={{ junos.facts.serialnumber }}      
