---
- name: Junos OS
  hosts: all
  connection: local
  gather_facts: no
  vars:
    restart_wait_time: 3600

  tasks:
    - include: tasks/check_nc

    - name: install Junos OS package
      junos_install_os:
        host={{ inventory_hostname }}
        version={{ OS_version }}
        package={{ pkg_dir }}/{{ OS_package }}
        logfile={{ log_dir }}/software.log
      register: sw
      notify:
        - Junos wait for restart

  handlers:
    - name: Junos wait for restart
      wait_for: host={{ inventory_hostname }} port=830 timeout={{ restart_wait_time }}
      when: not sw.check_mode
